name: CI/CD- Pipeline GitHub Actions on self-hosted

on:
  push:
    branches: [ AWS-Infrastructure ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #  EX2.a - Increase version
      - name: Bump version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE=$(echo $VERSION | cut -d. -f1,2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$BASE.$NEW_PATCH"

          mvn versions:set -DnewVersion=$NEW_VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      #  Build JAR
      - name: Build app
        run: /opt/maven/bin/mvn clean package -DskipTests

      #  Login to AWS
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1

      - name: Build Docker image for ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/java-app:${{ steps.version.outputs.version }}
          docker build -t $IMAGE_URI .

      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_URI

      - name: Deploy container
        run: |
          docker stop app || true
          docker rm app || true
          docker run -d -p 8080:8080 --name app $IMAGE_URI

      - name: Verify deployment
        run: docker logs app
